// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: internal/rpcpb/gateway.proto

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cursor        uint64                 `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_internal_rpcpb_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpcpb_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpcpb_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *WatchRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WatchRequest) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

// A wrapper preserves an explicit empty tag list in a host patch.
type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_internal_rpcpb_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpcpb_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_internal_rpcpb_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type Host struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Port          int64                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_internal_rpcpb_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpcpb_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_internal_rpcpb_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *Host) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Host) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Host) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Host) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Host) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type HostPatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          *string                `protobuf:"bytes,1,opt,name=addr,proto3,oneof" json:"addr,omitempty"`
	User          *string                `protobuf:"bytes,2,opt,name=user,proto3,oneof" json:"user,omitempty"`
	Port          *int64                 `protobuf:"varint,3,opt,name=port,proto3,oneof" json:"port,omitempty"`
	Key           *string                `protobuf:"bytes,4,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Tags          *StringList            `protobuf:"bytes,5,opt,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostPatch) Reset() {
	*x = HostPatch{}
	mi := &file_internal_rpcpb_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostPatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostPatch) ProtoMessage() {}

func (x *HostPatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpcpb_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostPatch.ProtoReflect.Descriptor instead.
func (*HostPatch) Descriptor() ([]byte, []int) {
	return file_internal_rpcpb_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *HostPatch) GetAddr() string {
	if x != nil && x.Addr != nil {
		return *x.Addr
	}
	return ""
}

func (x *HostPatch) GetUser() string {
	if x != nil && x.User != nil {
		return *x.User
	}
	return ""
}

func (x *HostPatch) GetPort() int64 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *HostPatch) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *HostPatch) GetTags() *StringList {
	if x != nil {
		return x.Tags
	}
	return nil
}

type PolicyDecision struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Action            string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Risk              string                 `protobuf:"bytes,2,opt,name=risk,proto3" json:"risk,omitempty"`
	RuleName          string                 `protobuf:"bytes,3,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	MatchedPattern    string                 `protobuf:"bytes,4,opt,name=matched_pattern,json=matchedPattern,proto3" json:"matched_pattern,omitempty"`
	Reason            string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	DefaultActionUsed bool                   `protobuf:"varint,6,opt,name=default_action_used,json=defaultActionUsed,proto3" json:"default_action_used,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PolicyDecision) Reset() {
	*x = PolicyDecision{}
	mi := &file_internal_rpcpb_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyDecision) ProtoMessage() {}

func (x *PolicyDecision) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpcpb_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyDecision.ProtoReflect.Descriptor instead.
func (*PolicyDecision) Descriptor() ([]byte, []int) {
	return file_internal_rpcpb_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *PolicyDecision) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PolicyDecision) GetRisk() string {
	if x != nil {
		return x.Risk
	}
	return ""
}

func (x *PolicyDecision) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *PolicyDecision) GetMatchedPattern() string {
	if x != nil {
		return x.MatchedPattern
	}
	return ""
}

func (x *PolicyDecision) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PolicyDecision) GetDefaultActionUsed() bool {
	if x != nil {
		return x.DefaultActionUsed
	}
	return false
}

type CommandRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Source          string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	ClientPid       int64                  `protobuf:"varint,6,opt,name=client_pid,json=clientPid,proto3" json:"client_pid,omitempty"`
	ClientCwd       string                 `protobuf:"bytes,7,opt,name=client_cwd,json=clientCwd,proto3" json:"client_cwd,omitempty"`
	Host            string                 `protobuf:"bytes,8,opt,name=host,proto3" json:"host,omitempty"`
	RemoteUser      string                 `protobuf:"bytes,9,opt,name=remote_user,json=remoteUser,proto3" json:"remote_user,omitempty"`
	Command         string                 `protobuf:"bytes,10,opt,name=command,proto3" json:"command,omitempty"`
	DisplayCommand  string                 `protobuf:"bytes,11,opt,name=display_command,json=displayCommand,proto3" json:"display_command,omitempty"`
	Mode            string                 `protobuf:"bytes,12,opt,name=mode,proto3" json:"mode,omitempty"`
	Risk            string                 `protobuf:"bytes,13,opt,name=risk,proto3" json:"risk,omitempty"`
	PolicyAction    string                 `protobuf:"bytes,14,opt,name=policy_action,json=policyAction,proto3" json:"policy_action,omitempty"`
	PolicyRule      string                 `protobuf:"bytes,15,opt,name=policy_rule,json=policyRule,proto3" json:"policy_rule,omitempty"`
	MatchedPattern  string                 `protobuf:"bytes,16,opt,name=matched_pattern,json=matchedPattern,proto3" json:"matched_pattern,omitempty"`
	PolicyReason    string                 `protobuf:"bytes,17,opt,name=policy_reason,json=policyReason,proto3" json:"policy_reason,omitempty"`
	DefaultAction   bool                   `protobuf:"varint,18,opt,name=default_action,json=defaultAction,proto3" json:"default_action,omitempty"`
	Status          string                 `protobuf:"bytes,19,opt,name=status,proto3" json:"status,omitempty"`
	RemoteExitCode  *int64                 `protobuf:"varint,20,opt,name=remote_exit_code,json=remoteExitCode,proto3,oneof" json:"remote_exit_code,omitempty"`
	SshUseErrorCode string                 `protobuf:"bytes,21,opt,name=ssh_use_error_code,json=sshUseErrorCode,proto3" json:"ssh_use_error_code,omitempty"`
	DurationMs      int64                  `protobuf:"varint,22,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Stdout          []byte                 `protobuf:"bytes,23,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr          []byte                 `protobuf:"bytes,24,opt,name=stderr,proto3" json:"stderr,omitempty"`
	StdoutTruncated bool                   `protobuf:"varint,25,opt,name=stdout_truncated,json=stdoutTruncated,proto3" json:"stdout_truncated,omitempty"`
	StderrTruncated bool                   `protobuf:"varint,26,opt,name=stderr_truncated,json=stderrTruncated,proto3" json:"stderr_truncated,omitempty"`
	Error           string                 `protobuf:"bytes,27,opt,name=error,proto3" json:"error,omitempty"`
	ApprovalStatus  string                 `protobuf:"bytes,28,opt,name=approval_status,json=approvalStatus,proto3" json:"approval_status,omitempty"`
	ApprovedAt      *timestamppb.Timestamp `protobuf:"bytes,29,opt,name=approved_at,json=approvedAt,proto3" json:"approved_at,omitempty"`
	PolicyDecision  *PolicyDecision        `protobuf:"bytes,30,opt,name=policy_decision,json=policyDecision,proto3" json:"policy_decision,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CommandRecord) Reset() {
	*x = CommandRecord{}
	mi := &file_internal_rpcpb_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRecord) ProtoMessage() {}

func (x *CommandRecord) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpcpb_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRecord.ProtoReflect.Descriptor instead.
func (*CommandRecord) Descriptor() ([]byte, []int) {
	return file_internal_rpcpb_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *CommandRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommandRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CommandRecord) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *CommandRecord) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *CommandRecord) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CommandRecord) GetClientPid() int64 {
	if x != nil {
		return x.ClientPid
	}
	return 0
}

func (x *CommandRecord) GetClientCwd() string {
	if x != nil {
		return x.ClientCwd
	}
	return ""
}

func (x *CommandRecord) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *CommandRecord) GetRemoteUser() string {
	if x != nil {
		return x.RemoteUser
	}
	return ""
}

func (x *CommandRecord) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandRecord) GetDisplayCommand() string {
	if x != nil {
		return x.DisplayCommand
	}
	return ""
}

func (x *CommandRecord) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *CommandRecord) GetRisk() string {
	if x != nil {
		return x.Risk
	}
	return ""
}

func (x *CommandRecord) GetPolicyAction() string {
	if x != nil {
		return x.PolicyAction
	}
	return ""
}

func (x *CommandRecord) GetPolicyRule() string {
	if x != nil {
		return x.PolicyRule
	}
	return ""
}

func (x *CommandRecord) GetMatchedPattern() string {
	if x != nil {
		return x.MatchedPattern
	}
	return ""
}

func (x *CommandRecord) GetPolicyReason() string {
	if x != nil {
		return x.PolicyReason
	}
	return ""
}

func (x *CommandRecord) GetDefaultAction() bool {
	if x != nil {
		return x.DefaultAction
	}
	return false
}

func (x *CommandRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CommandRecord) GetRemoteExitCode() int64 {
	if x != nil && x.RemoteExitCode != nil {
		return *x.RemoteExitCode
	}
	return 0
}

func (x *CommandRecord) GetSshUseErrorCode() string {
	if x != nil {
		return x.SshUseErrorCode
	}
	return ""
}

func (x *CommandRecord) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *CommandRecord) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *CommandRecord) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *CommandRecord) GetStdoutTruncated() bool {
	if x != nil {
		return x.StdoutTruncated
	}
	return false
}

func (x *CommandRecord) GetStderrTruncated() bool {
	if x != nil {
		return x.StderrTruncated
	}
	return false
}

func (x *CommandRecord) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandRecord) GetApprovalStatus() string {
	if x != nil {
		return x.ApprovalStatus
	}
	return ""
}

func (x *CommandRecord) GetApprovedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ApprovedAt
	}
	return nil
}

func (x *CommandRecord) GetPolicyDecision() *PolicyDecision {
	if x != nil {
		return x.PolicyDecision
	}
	return nil
}

type ConnectionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Addr          string                 `protobuf:"bytes,4,opt,name=addr,proto3" json:"addr,omitempty"`
	LastUsed      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_used,json=lastUsed,proto3" json:"last_used,omitempty"`
	ConnectedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	OpenSessions  int64                  `protobuf:"varint,7,opt,name=open_sessions,json=openSessions,proto3" json:"open_sessions,omitempty"`
	LastCommand   string                 `protobuf:"bytes,8,opt,name=last_command,json=lastCommand,proto3" json:"last_command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionStatus) Reset() {
	*x = ConnectionStatus{}
	mi := &file_internal_rpcpb_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionStatus) ProtoMessage() {}

func (x *ConnectionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpcpb_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionStatus.ProtoReflect.Descriptor instead.
func (*ConnectionStatus) Descriptor() ([]byte, []int) {
	return file_internal_rpcpb_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *ConnectionStatus) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ConnectionStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConnectionStatus) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ConnectionStatus) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ConnectionStatus) GetLastUsed() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsed
	}
	return nil
}

func (x *ConnectionStatus) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

func (x *ConnectionStatus) GetOpenSessions() int64 {
	if x != nil {
		return x.OpenSessions
	}
	return 0
}

func (x *ConnectionStatus) GetLastCommand() string {
	if x != nil {
		return x.LastCommand
	}
	return ""
}

type PolicyRuleView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Risk          string                 `protobuf:"bytes,3,opt,name=risk,proto3" json:"risk,omitempty"`
	Patterns      []string               `protobuf:"bytes,4,rep,name=patterns,proto3" json:"patterns,omitempty"`
	Matches       int64                  `protobuf:"varint,5,opt,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyRuleView) Reset() {
	*x = PolicyRuleView{}
	mi := &file_internal_rpcpb_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRuleView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRuleView) ProtoMessage() {}

func (x *PolicyRuleView) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpcpb_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRuleView.ProtoReflect.Descriptor instead.
func (*PolicyRuleView) Descriptor() ([]byte, []int) {
	return file_internal_rpcpb_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *PolicyRuleView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PolicyRuleView) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PolicyRuleView) GetRisk() string {
	if x != nil {
		return x.Risk
	}
	return ""
}

func (x *PolicyRuleView) GetPatterns() []string {
	if x != nil {
		return x.Patterns
	}
	return nil
}

func (x *PolicyRuleView) GetMatches() int64 {
	if x != nil {
		return x.Matches
	}
	return 0
}

type RuntimeSettings struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Generation          uint64                 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Mode                string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	PolicyDefaultAction string                 `protobuf:"bytes,3,opt,name=policy_default_action,json=policyDefaultAction,proto3" json:"policy_default_action,omitempty"`
	BuiltinRules        bool                   `protobuf:"varint,4,opt,name=builtin_rules,json=builtinRules,proto3" json:"builtin_rules,omitempty"`
	AuditStoreOutput    string                 `protobuf:"bytes,5,opt,name=audit_store_output,json=auditStoreOutput,proto3" json:"audit_store_output,omitempty"`
	AuditRetentionDays  int64                  `protobuf:"varint,6,opt,name=audit_retention_days,json=auditRetentionDays,proto3" json:"audit_retention_days,omitempty"`
	RedactSecrets       bool                   `protobuf:"varint,7,opt,name=redact_secrets,json=redactSecrets,proto3" json:"redact_secrets,omitempty"`
	ConfirmRisks        []string               `protobuf:"bytes,8,rep,name=confirm_risks,json=confirmRisks,proto3" json:"confirm_risks,omitempty"`
	Theme               string                 `protobuf:"bytes,9,opt,name=theme,proto3" json:"theme,omitempty"`
	FocusPending        bool                   `protobuf:"varint,10,opt,name=focus_pending,json=focusPending,proto3" json:"focus_pending,omitempty"`
	BellOnPending       bool                   `protobuf:"varint,11,opt,name=bell_on_pending,json=bellOnPending,proto3" json:"bell_on_pending,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RuntimeSettings) Reset() {
	*x = RuntimeSettings{}
	mi := &file_internal_rpcpb_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeSettings) ProtoMessage() {}

func (x *RuntimeSettings) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpcpb_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeSettings.ProtoReflect.Descriptor instead.
func (*RuntimeSettings) Descriptor() ([]byte, []int) {
	return file_internal_rpcpb_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *RuntimeSettings) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *RuntimeSettings) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *RuntimeSettings) GetPolicyDefaultAction() string {
	if x != nil {
		return x.PolicyDefaultAction
	}
	return ""
}

func (x *RuntimeSettings) GetBuiltinRules() bool {
	if x != nil {
		return x.BuiltinRules
	}
	return false
}

func (x *RuntimeSettings) GetAuditStoreOutput() string {
	if x != nil {
		return x.AuditStoreOutput
	}
	return ""
}

func (x *RuntimeSettings) GetAuditRetentionDays() int64 {
	if x != nil {
		return x.AuditRetentionDays
	}
	return 0
}

func (x *RuntimeSettings) GetRedactSecrets() bool {
	if x != nil {
		return x.RedactSecrets
	}
	return false
}

func (x *RuntimeSettings) GetConfirmRisks() []string {
	if x != nil {
		return x.ConfirmRisks
	}
	return nil
}

func (x *RuntimeSettings) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *RuntimeSettings) GetFocusPending() bool {
	if x != nil {
		return x.FocusPending
	}
	return false
}

func (x *RuntimeSettings) GetBellOnPending() bool {
	if x != nil {
		return x.BellOnPending
	}
	return false
}

type Message struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Cursor          uint64                 `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Version         int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	ConfigRevision  string                 `protobuf:"bytes,3,opt,name=config_revision,json=configRevision,proto3" json:"config_revision,omitempty"`
	HostConfig      *Host                  `protobuf:"bytes,4,opt,name=host_config,json=hostConfig,proto3" json:"host_config,omitempty"`
	HostPatch       *HostPatch             `protobuf:"bytes,5,opt,name=host_patch,json=hostPatch,proto3" json:"host_patch,omitempty"`
	Hosts           map[string]*Host       `protobuf:"bytes,6,rep,name=hosts,proto3" json:"hosts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Type            string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	RequestId       string                 `protobuf:"bytes,8,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Ok              bool                   `protobuf:"varint,9,opt,name=ok,proto3" json:"ok,omitempty"`
	Id              string                 `protobuf:"bytes,10,opt,name=id,proto3" json:"id,omitempty"`
	Host            string                 `protobuf:"bytes,11,opt,name=host,proto3" json:"host,omitempty"`
	Command         string                 `protobuf:"bytes,12,opt,name=command,proto3" json:"command,omitempty"`
	Source          string                 `protobuf:"bytes,13,opt,name=source,proto3" json:"source,omitempty"`
	Cwd             string                 `protobuf:"bytes,14,opt,name=cwd,proto3" json:"cwd,omitempty"`
	ClientPid       int64                  `protobuf:"varint,15,opt,name=client_pid,json=clientPid,proto3" json:"client_pid,omitempty"`
	Data            []byte                 `protobuf:"bytes,16,opt,name=data,proto3" json:"data,omitempty"`
	Seq             int64                  `protobuf:"varint,17,opt,name=seq,proto3" json:"seq,omitempty"`
	Status          string                 `protobuf:"bytes,18,opt,name=status,proto3" json:"status,omitempty"`
	RemoteExitCode  *int64                 `protobuf:"varint,19,opt,name=remote_exit_code,json=remoteExitCode,proto3,oneof" json:"remote_exit_code,omitempty"`
	SshUseErrorCode string                 `protobuf:"bytes,20,opt,name=ssh_use_error_code,json=sshUseErrorCode,proto3" json:"ssh_use_error_code,omitempty"`
	Error           string                 `protobuf:"bytes,21,opt,name=error,proto3" json:"error,omitempty"`
	Decision        string                 `protobuf:"bytes,22,opt,name=decision,proto3" json:"decision,omitempty"`
	Paused          bool                   `protobuf:"varint,23,opt,name=paused,proto3" json:"paused,omitempty"`
	Mode            string                 `protobuf:"bytes,24,opt,name=mode,proto3" json:"mode,omitempty"`
	Direction       string                 `protobuf:"bytes,25,opt,name=direction,proto3" json:"direction,omitempty"`
	LocalPath       string                 `protobuf:"bytes,26,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	RemotePath      string                 `protobuf:"bytes,27,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	Size            int64                  `protobuf:"varint,28,opt,name=size,proto3" json:"size,omitempty"`
	Bytes           int64                  `protobuf:"varint,29,opt,name=bytes,proto3" json:"bytes,omitempty"`
	FileMode        uint32                 `protobuf:"varint,30,opt,name=file_mode,json=fileMode,proto3" json:"file_mode,omitempty"`
	PreserveMode    bool                   `protobuf:"varint,31,opt,name=preserve_mode,json=preserveMode,proto3" json:"preserve_mode,omitempty"`
	Atomic          bool                   `protobuf:"varint,32,opt,name=atomic,proto3" json:"atomic,omitempty"`
	Checksum        string                 `protobuf:"bytes,33,opt,name=checksum,proto3" json:"checksum,omitempty"`
	TuiConnected    bool                   `protobuf:"varint,34,opt,name=tui_connected,json=tuiConnected,proto3" json:"tui_connected,omitempty"`
	Elapsed         string                 `protobuf:"bytes,35,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	Position        int64                  `protobuf:"varint,36,opt,name=position,proto3" json:"position,omitempty"`
	Record          *CommandRecord         `protobuf:"bytes,37,opt,name=record,proto3" json:"record,omitempty"`
	Commands        []*CommandRecord       `protobuf:"bytes,38,rep,name=commands,proto3" json:"commands,omitempty"`
	Connections     []*ConnectionStatus    `protobuf:"bytes,39,rep,name=connections,proto3" json:"connections,omitempty"`
	PolicyRules     []*PolicyRuleView      `protobuf:"bytes,40,rep,name=policy_rules,json=policyRules,proto3" json:"policy_rules,omitempty"`
	Revision        uint64                 `protobuf:"varint,41,opt,name=revision,proto3" json:"revision,omitempty"`
	PolicyDecision  *PolicyDecision        `protobuf:"bytes,42,opt,name=policy_decision,json=policyDecision,proto3" json:"policy_decision,omitempty"`
	RuntimeSettings *RuntimeSettings       `protobuf:"bytes,43,opt,name=runtime_settings,json=runtimeSettings,proto3" json:"runtime_settings,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_internal_rpcpb_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpcpb_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_internal_rpcpb_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *Message) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *Message) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Message) GetConfigRevision() string {
	if x != nil {
		return x.ConfigRevision
	}
	return ""
}

func (x *Message) GetHostConfig() *Host {
	if x != nil {
		return x.HostConfig
	}
	return nil
}

func (x *Message) GetHostPatch() *HostPatch {
	if x != nil {
		return x.HostPatch
	}
	return nil
}

func (x *Message) GetHosts() map[string]*Host {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Message) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Message) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Message) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Message) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *Message) GetClientPid() int64 {
	if x != nil {
		return x.ClientPid
	}
	return 0
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Message) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Message) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Message) GetRemoteExitCode() int64 {
	if x != nil && x.RemoteExitCode != nil {
		return *x.RemoteExitCode
	}
	return 0
}

func (x *Message) GetSshUseErrorCode() string {
	if x != nil {
		return x.SshUseErrorCode
	}
	return ""
}

func (x *Message) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Message) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *Message) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

func (x *Message) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Message) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *Message) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *Message) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

func (x *Message) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Message) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *Message) GetFileMode() uint32 {
	if x != nil {
		return x.FileMode
	}
	return 0
}

func (x *Message) GetPreserveMode() bool {
	if x != nil {
		return x.PreserveMode
	}
	return false
}

func (x *Message) GetAtomic() bool {
	if x != nil {
		return x.Atomic
	}
	return false
}

func (x *Message) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *Message) GetTuiConnected() bool {
	if x != nil {
		return x.TuiConnected
	}
	return false
}

func (x *Message) GetElapsed() string {
	if x != nil {
		return x.Elapsed
	}
	return ""
}

func (x *Message) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Message) GetRecord() *CommandRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *Message) GetCommands() []*CommandRecord {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *Message) GetConnections() []*ConnectionStatus {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *Message) GetPolicyRules() []*PolicyRuleView {
	if x != nil {
		return x.PolicyRules
	}
	return nil
}

func (x *Message) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Message) GetPolicyDecision() *PolicyDecision {
	if x != nil {
		return x.PolicyDecision
	}
	return nil
}

func (x *Message) GetRuntimeSettings() *RuntimeSettings {
	if x != nil {
		return x.RuntimeSettings
	}
	return nil
}

var File_internal_rpcpb_gateway_proto protoreflect.FileDescriptor

const file_internal_rpcpb_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/rpcpb/gateway.proto\x12\tsshuse.v2\x1a\x1fgoogle/protobuf/timestamp.proto\"6\n" +
	"\fWatchRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x04R\x06cursor\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"h\n" +
	"\x04Host\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x03R\x04port\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"\xbb\x01\n" +
	"\tHostPatch\x12\x17\n" +
	"\x04addr\x18\x01 \x01(\tH\x00R\x04addr\x88\x01\x01\x12\x17\n" +
	"\x04user\x18\x02 \x01(\tH\x01R\x04user\x88\x01\x01\x12\x17\n" +
	"\x04port\x18\x03 \x01(\x03H\x02R\x04port\x88\x01\x01\x12\x15\n" +
	"\x03key\x18\x04 \x01(\tH\x03R\x03key\x88\x01\x01\x12)\n" +
	"\x04tags\x18\x05 \x01(\v2\x15.sshuse.v2.StringListR\x04tagsB\a\n" +
	"\x05_addrB\a\n" +
	"\x05_userB\a\n" +
	"\x05_portB\x06\n" +
	"\x04_key\"\xca\x01\n" +
	"\x0ePolicyDecision\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x12\n" +
	"\x04risk\x18\x02 \x01(\tR\x04risk\x12\x1b\n" +
	"\trule_name\x18\x03 \x01(\tR\bruleName\x12'\n" +
	"\x0fmatched_pattern\x18\x04 \x01(\tR\x0ematchedPattern\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12.\n" +
	"\x13default_action_used\x18\x06 \x01(\bR\x11defaultActionUsed\"\xf3\b\n" +
	"\rCommandRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"client_pid\x18\x06 \x01(\x03R\tclientPid\x12\x1d\n" +
	"\n" +
	"client_cwd\x18\a \x01(\tR\tclientCwd\x12\x12\n" +
	"\x04host\x18\b \x01(\tR\x04host\x12\x1f\n" +
	"\vremote_user\x18\t \x01(\tR\n" +
	"remoteUser\x12\x18\n" +
	"\acommand\x18\n" +
	" \x01(\tR\acommand\x12'\n" +
	"\x0fdisplay_command\x18\v \x01(\tR\x0edisplayCommand\x12\x12\n" +
	"\x04mode\x18\f \x01(\tR\x04mode\x12\x12\n" +
	"\x04risk\x18\r \x01(\tR\x04risk\x12#\n" +
	"\rpolicy_action\x18\x0e \x01(\tR\fpolicyAction\x12\x1f\n" +
	"\vpolicy_rule\x18\x0f \x01(\tR\n" +
	"policyRule\x12'\n" +
	"\x0fmatched_pattern\x18\x10 \x01(\tR\x0ematchedPattern\x12#\n" +
	"\rpolicy_reason\x18\x11 \x01(\tR\fpolicyReason\x12%\n" +
	"\x0edefault_action\x18\x12 \x01(\bR\rdefaultAction\x12\x16\n" +
	"\x06status\x18\x13 \x01(\tR\x06status\x12-\n" +
	"\x10remote_exit_code\x18\x14 \x01(\x03H\x00R\x0eremoteExitCode\x88\x01\x01\x12+\n" +
	"\x12ssh_use_error_code\x18\x15 \x01(\tR\x0fsshUseErrorCode\x12\x1f\n" +
	"\vduration_ms\x18\x16 \x01(\x03R\n" +
	"durationMs\x12\x16\n" +
	"\x06stdout\x18\x17 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x18 \x01(\fR\x06stderr\x12)\n" +
	"\x10stdout_truncated\x18\x19 \x01(\bR\x0fstdoutTruncated\x12)\n" +
	"\x10stderr_truncated\x18\x1a \x01(\bR\x0fstderrTruncated\x12\x14\n" +
	"\x05error\x18\x1b \x01(\tR\x05error\x12'\n" +
	"\x0fapproval_status\x18\x1c \x01(\tR\x0eapprovalStatus\x12;\n" +
	"\vapproved_at\x18\x1d \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"approvedAt\x12B\n" +
	"\x0fpolicy_decision\x18\x1e \x01(\v2\x19.sshuse.v2.PolicyDecisionR\x0epolicyDecisionB\x13\n" +
	"\x11_remote_exit_code\"\xa6\x02\n" +
	"\x10ConnectionStatus\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x12\n" +
	"\x04addr\x18\x04 \x01(\tR\x04addr\x127\n" +
	"\tlast_used\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\blastUsed\x12=\n" +
	"\fconnected_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\x12#\n" +
	"\ropen_sessions\x18\a \x01(\x03R\fopenSessions\x12!\n" +
	"\flast_command\x18\b \x01(\tR\vlastCommand\"\x86\x01\n" +
	"\x0ePolicyRuleView\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x12\n" +
	"\x04risk\x18\x03 \x01(\tR\x04risk\x12\x1a\n" +
	"\bpatterns\x18\x04 \x03(\tR\bpatterns\x12\x18\n" +
	"\amatches\x18\x05 \x01(\x03R\amatches\"\xad\x03\n" +
	"\x0fRuntimeSettings\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x122\n" +
	"\x15policy_default_action\x18\x03 \x01(\tR\x13policyDefaultAction\x12#\n" +
	"\rbuiltin_rules\x18\x04 \x01(\bR\fbuiltinRules\x12,\n" +
	"\x12audit_store_output\x18\x05 \x01(\tR\x10auditStoreOutput\x120\n" +
	"\x14audit_retention_days\x18\x06 \x01(\x03R\x12auditRetentionDays\x12%\n" +
	"\x0eredact_secrets\x18\a \x01(\bR\rredactSecrets\x12#\n" +
	"\rconfirm_risks\x18\b \x03(\tR\fconfirmRisks\x12\x14\n" +
	"\x05theme\x18\t \x01(\tR\x05theme\x12#\n" +
	"\rfocus_pending\x18\n" +
	" \x01(\bR\ffocusPending\x12&\n" +
	"\x0fbell_on_pending\x18\v \x01(\bR\rbellOnPending\"\x87\f\n" +
	"\aMessage\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\x04R\x06cursor\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12'\n" +
	"\x0fconfig_revision\x18\x03 \x01(\tR\x0econfigRevision\x120\n" +
	"\vhost_config\x18\x04 \x01(\v2\x0f.sshuse.v2.HostR\n" +
	"hostConfig\x123\n" +
	"\n" +
	"host_patch\x18\x05 \x01(\v2\x14.sshuse.v2.HostPatchR\thostPatch\x123\n" +
	"\x05hosts\x18\x06 \x03(\v2\x1d.sshuse.v2.Message.HostsEntryR\x05hosts\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"request_id\x18\b \x01(\tR\trequestId\x12\x0e\n" +
	"\x02ok\x18\t \x01(\bR\x02ok\x12\x0e\n" +
	"\x02id\x18\n" +
	" \x01(\tR\x02id\x12\x12\n" +
	"\x04host\x18\v \x01(\tR\x04host\x12\x18\n" +
	"\acommand\x18\f \x01(\tR\acommand\x12\x16\n" +
	"\x06source\x18\r \x01(\tR\x06source\x12\x10\n" +
	"\x03cwd\x18\x0e \x01(\tR\x03cwd\x12\x1d\n" +
	"\n" +
	"client_pid\x18\x0f \x01(\x03R\tclientPid\x12\x12\n" +
	"\x04data\x18\x10 \x01(\fR\x04data\x12\x10\n" +
	"\x03seq\x18\x11 \x01(\x03R\x03seq\x12\x16\n" +
	"\x06status\x18\x12 \x01(\tR\x06status\x12-\n" +
	"\x10remote_exit_code\x18\x13 \x01(\x03H\x00R\x0eremoteExitCode\x88\x01\x01\x12+\n" +
	"\x12ssh_use_error_code\x18\x14 \x01(\tR\x0fsshUseErrorCode\x12\x14\n" +
	"\x05error\x18\x15 \x01(\tR\x05error\x12\x1a\n" +
	"\bdecision\x18\x16 \x01(\tR\bdecision\x12\x16\n" +
	"\x06paused\x18\x17 \x01(\bR\x06paused\x12\x12\n" +
	"\x04mode\x18\x18 \x01(\tR\x04mode\x12\x1c\n" +
	"\tdirection\x18\x19 \x01(\tR\tdirection\x12\x1d\n" +
	"\n" +
	"local_path\x18\x1a \x01(\tR\tlocalPath\x12\x1f\n" +
	"\vremote_path\x18\x1b \x01(\tR\n" +
	"remotePath\x12\x12\n" +
	"\x04size\x18\x1c \x01(\x03R\x04size\x12\x14\n" +
	"\x05bytes\x18\x1d \x01(\x03R\x05bytes\x12\x1b\n" +
	"\tfile_mode\x18\x1e \x01(\rR\bfileMode\x12#\n" +
	"\rpreserve_mode\x18\x1f \x01(\bR\fpreserveMode\x12\x16\n" +
	"\x06atomic\x18  \x01(\bR\x06atomic\x12\x1a\n" +
	"\bchecksum\x18! \x01(\tR\bchecksum\x12#\n" +
	"\rtui_connected\x18\" \x01(\bR\ftuiConnected\x12\x18\n" +
	"\aelapsed\x18# \x01(\tR\aelapsed\x12\x1a\n" +
	"\bposition\x18$ \x01(\x03R\bposition\x120\n" +
	"\x06record\x18% \x01(\v2\x18.sshuse.v2.CommandRecordR\x06record\x124\n" +
	"\bcommands\x18& \x03(\v2\x18.sshuse.v2.CommandRecordR\bcommands\x12=\n" +
	"\vconnections\x18' \x03(\v2\x1b.sshuse.v2.ConnectionStatusR\vconnections\x12<\n" +
	"\fpolicy_rules\x18( \x03(\v2\x19.sshuse.v2.PolicyRuleViewR\vpolicyRules\x12\x1a\n" +
	"\brevision\x18) \x01(\x04R\brevision\x12B\n" +
	"\x0fpolicy_decision\x18* \x01(\v2\x19.sshuse.v2.PolicyDecisionR\x0epolicyDecision\x12E\n" +
	"\x10runtime_settings\x18+ \x01(\v2\x1a.sshuse.v2.RuntimeSettingsR\x0fruntimeSettings\x1aI\n" +
	"\n" +
	"HostsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.sshuse.v2.HostR\x05value:\x028\x01B\x13\n" +
	"\x11_remote_exit_code2\xa2\x02\n" +
	"\aGateway\x121\n" +
	"\aRequest\x12\x12.sshuse.v2.Message\x1a\x12.sshuse.v2.Message\x123\n" +
	"\tSubmitJob\x12\x12.sshuse.v2.Message\x1a\x12.sshuse.v2.Message\x129\n" +
	"\bWatchJob\x12\x17.sshuse.v2.WatchRequest\x1a\x12.sshuse.v2.Message0\x01\x12<\n" +
	"\vWatchEvents\x12\x17.sshuse.v2.WatchRequest\x1a\x12.sshuse.v2.Message0\x01\x126\n" +
	"\bTransfer\x12\x12.sshuse.v2.Message\x1a\x12.sshuse.v2.Message(\x010\x01B+Z)github.com/zhiylee/ssh-use/internal/rpcpbb\x06proto3"

var (
	file_internal_rpcpb_gateway_proto_rawDescOnce sync.Once
	file_internal_rpcpb_gateway_proto_rawDescData []byte
)

func file_internal_rpcpb_gateway_proto_rawDescGZIP() []byte {
	file_internal_rpcpb_gateway_proto_rawDescOnce.Do(func() {
		file_internal_rpcpb_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_rpcpb_gateway_proto_rawDesc), len(file_internal_rpcpb_gateway_proto_rawDesc)))
	})
	return file_internal_rpcpb_gateway_proto_rawDescData
}

var file_internal_rpcpb_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_rpcpb_gateway_proto_goTypes = []any{
	(*WatchRequest)(nil),          // 0: sshuse.v2.WatchRequest
	(*StringList)(nil),            // 1: sshuse.v2.StringList
	(*Host)(nil),                  // 2: sshuse.v2.Host
	(*HostPatch)(nil),             // 3: sshuse.v2.HostPatch
	(*PolicyDecision)(nil),        // 4: sshuse.v2.PolicyDecision
	(*CommandRecord)(nil),         // 5: sshuse.v2.CommandRecord
	(*ConnectionStatus)(nil),      // 6: sshuse.v2.ConnectionStatus
	(*PolicyRuleView)(nil),        // 7: sshuse.v2.PolicyRuleView
	(*RuntimeSettings)(nil),       // 8: sshuse.v2.RuntimeSettings
	(*Message)(nil),               // 9: sshuse.v2.Message
	nil,                           // 10: sshuse.v2.Message.HostsEntry
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_internal_rpcpb_gateway_proto_depIdxs = []int32{
	1,  // 0: sshuse.v2.HostPatch.tags:type_name -> sshuse.v2.StringList
	11, // 1: sshuse.v2.CommandRecord.created_at:type_name -> google.protobuf.Timestamp
	11, // 2: sshuse.v2.CommandRecord.started_at:type_name -> google.protobuf.Timestamp
	11, // 3: sshuse.v2.CommandRecord.finished_at:type_name -> google.protobuf.Timestamp
	11, // 4: sshuse.v2.CommandRecord.approved_at:type_name -> google.protobuf.Timestamp
	4,  // 5: sshuse.v2.CommandRecord.policy_decision:type_name -> sshuse.v2.PolicyDecision
	11, // 6: sshuse.v2.ConnectionStatus.last_used:type_name -> google.protobuf.Timestamp
	11, // 7: sshuse.v2.ConnectionStatus.connected_at:type_name -> google.protobuf.Timestamp
	2,  // 8: sshuse.v2.Message.host_config:type_name -> sshuse.v2.Host
	3,  // 9: sshuse.v2.Message.host_patch:type_name -> sshuse.v2.HostPatch
	10, // 10: sshuse.v2.Message.hosts:type_name -> sshuse.v2.Message.HostsEntry
	5,  // 11: sshuse.v2.Message.record:type_name -> sshuse.v2.CommandRecord
	5,  // 12: sshuse.v2.Message.commands:type_name -> sshuse.v2.CommandRecord
	6,  // 13: sshuse.v2.Message.connections:type_name -> sshuse.v2.ConnectionStatus
	7,  // 14: sshuse.v2.Message.policy_rules:type_name -> sshuse.v2.PolicyRuleView
	4,  // 15: sshuse.v2.Message.policy_decision:type_name -> sshuse.v2.PolicyDecision
	8,  // 16: sshuse.v2.Message.runtime_settings:type_name -> sshuse.v2.RuntimeSettings
	2,  // 17: sshuse.v2.Message.HostsEntry.value:type_name -> sshuse.v2.Host
	9,  // 18: sshuse.v2.Gateway.Request:input_type -> sshuse.v2.Message
	9,  // 19: sshuse.v2.Gateway.SubmitJob:input_type -> sshuse.v2.Message
	0,  // 20: sshuse.v2.Gateway.WatchJob:input_type -> sshuse.v2.WatchRequest
	0,  // 21: sshuse.v2.Gateway.WatchEvents:input_type -> sshuse.v2.WatchRequest
	9,  // 22: sshuse.v2.Gateway.Transfer:input_type -> sshuse.v2.Message
	9,  // 23: sshuse.v2.Gateway.Request:output_type -> sshuse.v2.Message
	9,  // 24: sshuse.v2.Gateway.SubmitJob:output_type -> sshuse.v2.Message
	9,  // 25: sshuse.v2.Gateway.WatchJob:output_type -> sshuse.v2.Message
	9,  // 26: sshuse.v2.Gateway.WatchEvents:output_type -> sshuse.v2.Message
	9,  // 27: sshuse.v2.Gateway.Transfer:output_type -> sshuse.v2.Message
	23, // [23:28] is the sub-list for method output_type
	18, // [18:23] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_internal_rpcpb_gateway_proto_init() }
func file_internal_rpcpb_gateway_proto_init() {
	if File_internal_rpcpb_gateway_proto != nil {
		return
	}
	file_internal_rpcpb_gateway_proto_msgTypes[3].OneofWrappers = []any{}
	file_internal_rpcpb_gateway_proto_msgTypes[5].OneofWrappers = []any{}
	file_internal_rpcpb_gateway_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_rpcpb_gateway_proto_rawDesc), len(file_internal_rpcpb_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_rpcpb_gateway_proto_goTypes,
		DependencyIndexes: file_internal_rpcpb_gateway_proto_depIdxs,
		MessageInfos:      file_internal_rpcpb_gateway_proto_msgTypes,
	}.Build()
	File_internal_rpcpb_gateway_proto = out.File
	file_internal_rpcpb_gateway_proto_goTypes = nil
	file_internal_rpcpb_gateway_proto_depIdxs = nil
}
